# Generated by Django 4.0.6 on 2022-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_alter_directory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, upload_to='user_data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
